### ISSUE TITLE
i got a wrong info,

### ISSUE THREAD

**Issue by webstermobile** [vigetlabs/blendid#389]
fs.js:945
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir 'D:\MyApp\node_modules\.3.13.1@node-sass\vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:945:18)
    at Object.getInstalledBinaries (D:\MyApp\node_modules\.3.13.1@node-sass\lib\extensions.js:121:13)
    at foundBinariesList (D:\MyApp\node_modules\.3.13.1@node-sass\lib\errors.js:20:15)
    at foundBinaries (D:\MyApp\node_modules\.3.13.1@node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (D:\MyApp\node_modules\.3.13.1@node-sass\lib\errors.js:45:5)
    at module.exports (D:\MyApp\node_modules\.3.13.1@node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (D:\MyApp\node_modules\.3.13.1@node-sass\lib\index.js:14:35)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)

**Comment by greypants** [comment]
Not really enough to go on... did you ever get this working? Try again with Blendid.
