### ISSUE TITLE
Build error EXDEV

### ISSUE THREAD

**Issue by light-flight** [vigetlabs/blendid#415]
Crashes on task '**replaceFiles**' and 'build' on the line `fs.renameSync`
Error: EXDEV: cross-device link not permitted, rename '/tmp/gulp-starter' -> '/home/PATH_TO_APP/public'
http://stackoverflow.com/a/21072354

**Comment by greypants** [comment]
Thanks for reporting. What's your setup? I believe I've heard of this happening sometimes with Vagrant setups, and it has to do with `os.tmpdir()` being in an inaccessible location.  In your `path-config.json`, you can add a `tmp: 'some/other/path`` property to specify a different temp directory to build to.

This is a good reminder that I need to document this!

**Comment by greypants** [comment]
Did changing the tpm directory fix your issue?

**Comment by light-flight** [comment]
sorry for silence, mate. i've tried, but it didn't make any changes

**Comment by light-flight** [comment]
Huh, there is stupid mistake 

> `"tmp": "some/other/path"`

**Not `tmp` but `temp`**

**Comment by kevnk** [comment]
This happened to me on a vagrant setup. Adding this to my `path-config.json` fixed it:

```json
{
  ...
  "temp": "../temp",
  ...
}
```

**Comment by Seminioni** [comment]
Previous comment helped me too. 
I am on W10, Bash through Windows Linux Subsystem.

**Comment by devinle** [comment]
I implemented this change, and I'm using DeployBot. I'm still seeing the following error. Any ideas?

output [16:21:13] Starting 'replaceFiles'...
output [16:21:13] 'replaceFiles' errored after 3.37 ms
output [16:21:13] Error: EXDEV: cross-device link not permitted, rename '/temp' -> '/source/public'
output at Error (native)
output at Object.fs.renameSync (fs.js:809:18)
output at Gulp.replaceFiles (/source/node_modules/blendid/gulpfile.js/tasks/replace-files.js:10:6)
output at module.exports (/source/node_modules/orchestrator/lib/runTask.js:34:7)
output at Gulp.Orchestrator._runTask (/source/node_modules/orchestrator/index.js:273:3)
output at Gulp.Orchestrator._runStep (/source/node_modules/orchestrator/index.js:214:10)
output at Gulp.Orchestrator.start (/source/node_modules/orchestrator/index.js:134:8)
output at /source/node_modules/gulp-sequence/index.js:68:12
output at apply (/source/node_modules/thunks/thunks.js:354:38)
output at tryRun (/source/node_modules/thunks/thunks.js:224:19)
output [16:21:13] 'build' errored after 1.62 s

**Comment by devinle** [comment]
Hi @kevnk 

Thanks for the quick response. I actually just got this working by using ./ instead of ../
Seems to be doing the trick now!

{
  ...
  "temp": "./temp",
  ...
}
