### ISSUE TITLE
Error on first install

### ISSUE THREAD

**Issue by heathflohre** [vigetlabs/blendid#458]
Geeting this error when doing the first install.

➜  test yarn run blendid -- init
yarn run v0.24.6
$ "/Users/heath/Desktop/test/node_modules/.bin/blendid" init
[12:25:17] Working directory changed to ~/Desktop/test/node_modules/blendid
/Users/heath/Desktop/test/node_modules/require-dir/index.js:97
            if (!require.extensions.hasOwnProperty(ext)) {
                                    ^

TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (/Users/heath/Desktop/test/node_modules/require-dir/index.js:97:37)
    at Object.<anonymous> (/Users/heath/Desktop/test/node_modules/blendid/gulpfile.js/index.js:22:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Liftoff.handleArguments (/Users/heath/Desktop/test/node_modules/gulp/bin/gulp.js:116:3)
✨  Done in 0.33s.

**Comment by greypants** [comment]
What version of Node?

**Comment by greypants** [comment]
Looks like it was `require-dir` bug on Node 8. https://github.com/aseemk/requireDir/issues/45

I need to updated the dependency.

**Comment by heathflohre** [comment]
It is v8.

**Comment by outoftime** [comment]
Blendid has an dependency on [`require-dir` 0.3.1](https://github.com/vigetlabs/blendid/blob/master/package.json#L60), so fixing this requires an upgrade to Blendid.

Is there a reason this project doesn’t use semver dependencies?

**Comment by nothingrandom** [comment]
@heathflohre 

To fix this (until someone makes the upgrade to blendid, you need to be running a version of node earlier than 8 (can confirm that's the cause from just trying to install myself).

If you install node 6.11.0 through [nvm](https://github.com/creationix/nvm).
```
$ wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
$ nvm install 6.11.0
$ nvm use 6.11.0
```

Delete the node_nodules file and run the `yarn add blendid` command again.

**Comment by ryanlloydfrench** [comment]
@nothingrandom Thanks, this works for now.

**Comment by greypants** [comment]
4.2.0 works w/node 8 now.
